x-common-variables: &common-variables
  BOT_TOKEN: "*"
  ANTHROPIC_API_KEY: "*"

services:
  app:
    build: .
    environment:
      <<: *common-variables
    command: sh -c "cd code && python bot.py"
    restart: unless-stopped
