x-common-variables: &common-variables

services:
  app:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./code:/app/code
    environment:
      BOT_TOKEN: '*'
      ANTHROPIC_API_KEY: '*'

    command: python -m code.bot

networks:
  default:
    name: app-network
    external: true
