x-common-variables: &common-variables
  BOT_TOKEN: '*'
  ANTHROPIC_API_KEY: '*'


services:
  app:
    build: .
    ports:
      - "8001:8000"
    volumes:
      - ./code:/app/code
    environment:
      <<: *common-variables
    command: sh -c "cd code && python bot.py"
